server:
  port: 8090
spring:
  application:
    name: bank-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lenyn15/bank-config
  security:
    user:
      name: root
      password: v4L1d0
